### ISSUE TITLE
Importing messages from Maildir resets time

### ISSUE THREAD

**Issue by rudihorn** [stalwartlabs/jmap-server-cli#1]
I tried importing emails to stalwart from a Maildir folder and it seems that all the dates from the emails are reset to the time they were imported rather than the original time of the message. I'm using the Team Mail app and the `Date:` header in the offline emails are still correct.

**Comment by mdecimus** [comment]
Maildir uses the file's creation date as the message's Received date. Are the dates on the files correct?

**Comment by rudihorn** [comment]
Right so I suspect they may not have been, but when I redid this experiment using mbsync's `CopyArrivalDate yes` option I still ran into the same issue. From what I can tell, stalwart client is using the change time (`ls -c`) rather than the creation time which I have confirmed are correct.

**Comment by mdecimus** [comment]
Sorry for the confusion, Rust calls it creation date but on Linux it is using the modify date. So if you do a ``stat`` on one of the messages, the date that the CLI will use is what shows on the ``Modify`` field:

```bash
stat message.eml
  File: message.eml
  Size: 2               Blocks: 8          IO Block: 4096   regular file
Device: 801h/2049d      Inode: 1805443     Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/ vagrant)   Gid: ( 1000/ vagrant)
Access: 2022-10-05 09:22:14.064048193 +0000
Modify: 2022-08-10 12:18:55.039992638 +0000
Change: 2022-10-05 09:22:13.996048929 +0000
Birth: -
```

I did a quick test on a Maildir folder and added a flag to a message, the Modify date remained the same but both the Access and Change dates changed to when the flag was added.

**Comment by rudihorn** [comment]
So a quick test with a file from mbsync on Ubuntu yields the following:
```
  Size: 50615           Blocks: 104        IO Block: 4096   regular file
Device: fd01h/64769d    Inode: 1707786     Links: 1
Access: (0600/-rw-------)  Uid: ( 1000/administrator)   Gid: ( 1000/administrator)
Access: 2020-08-17 13:47:27.000000000 +0000
Modify: 2020-08-17 13:47:27.000000000 +0000
Change: 2022-10-06 06:02:13.036664855 +0000
 Birth: 2022-10-06 06:02:13.024664850 +0000
```
`ls` shows the modify date I assume.

**Comment by mdecimus** [comment]
@rudihorn Are you still having problems with the import dates or may I close this issue?

**Comment by rudihorn** [comment]
@mdecimus from what I can tell the CLI is still not using the modify date and instead using one of the other dates (either change or birth). I assume this is not the correct behaviour. I can see if I can find some time to look into the more explicit Rust details this weekend.
